### ISSUE TITLE
Hello, not an issue but a question uwu

### ISSUE THREAD

**Issue by msaenzy** [mikeaalv/image_seg_sorghum_am#3]
Hiiii, I`m an Uni student from Ecuador, I`m working on a computer vision program to identify mycorrizah in microscopic pictures, I`m a bit lost with my project trying to find datasets from the 3 kinds of mycorrizah, I`m wondering if you could help me with the explanation of the datasets you have, Does your dataset have the 3 kinds of mycorrizah? cause i would appreciate to know the classification of your dataset, or if you could guide me with my project cause i`m a bit lost with computer vision

Thank you so much for your time and understanding <3

**Comment by mikeaalv** [comment]
Hi, Thanks for reaching out. The latest repo is [here](https://github.com/Arnold-Lab/image_seg_sorghum_am) and we just published a [paper](https://www.nature.com/articles/s41598-024-61181-5#citeas) on the results. The first author Shufan is continuing the project. Feel free to email us if you have questions after the readings.
